// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpZ2_QdP-7CZIdKu_ZpxLWlEDDL74aZN8',
    appId: '1:674449858390:web:77709e74db6c4edb47c0f7',
    messagingSenderId: '674449858390',
    projectId: 'exam2-9aa9d',
    authDomain: 'exam2-9aa9d.firebaseapp.com',
    storageBucket: 'exam2-9aa9d.appspot.com',
    measurementId: 'G-EQ4H0K0S40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsA6zWXwc_7YgmfloNXfQ7ayLzan1rvf4',
    appId: '1:674449858390:android:a7951231d5f208da47c0f7',
    messagingSenderId: '674449858390',
    projectId: 'exam2-9aa9d',
    storageBucket: 'exam2-9aa9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClcOOyZXFAYfFjQtRj7YXPlAIjnnpl6_M',
    appId: '1:674449858390:ios:ef040ccb2ada19f047c0f7',
    messagingSenderId: '674449858390',
    projectId: 'exam2-9aa9d',
    storageBucket: 'exam2-9aa9d.appspot.com',
    iosBundleId: 'com.example.exam2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClcOOyZXFAYfFjQtRj7YXPlAIjnnpl6_M',
    appId: '1:674449858390:ios:ef040ccb2ada19f047c0f7',
    messagingSenderId: '674449858390',
    projectId: 'exam2-9aa9d',
    storageBucket: 'exam2-9aa9d.appspot.com',
    iosBundleId: 'com.example.exam2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpZ2_QdP-7CZIdKu_ZpxLWlEDDL74aZN8',
    appId: '1:674449858390:web:e202e026de4f2f5a47c0f7',
    messagingSenderId: '674449858390',
    projectId: 'exam2-9aa9d',
    authDomain: 'exam2-9aa9d.firebaseapp.com',
    storageBucket: 'exam2-9aa9d.appspot.com',
    measurementId: 'G-2PPB83G0QS',
  );
}
